all:	CSInvite.exe

CSInvite.exe:	CSInvite.c
	gcc -Wall CSInvite.c print_strings.c CSInvite_help.c CSInvite_set_input.c CSInvite_set_vars.c CSInvite_set_func.c -o CSInvite.exe

clean:
	rm CSInvite.exe
